// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

import { config } from 'dotenv'
import { defineConfig, env } from '@prisma/config'

config({ path: '.env.local' })  // or '.env' if you use that

export default defineConfig({
  datasource: {
    url: env('DATABASE_URL'),
  },
})