FROM golang:1.23-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/prober ./cmd/prober

FROM gcr.io/distroless/static-debian12
COPY --from=builder /bin/prober /prober
ENTRYPOINT ["/prober"]
