FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/notary ./cmd/notary

FROM gcr.io/distroless/static-debian12
EXPOSE 9092
COPY --from=builder /bin/notary /notary
ENTRYPOINT ["/notary"]
