// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/metrics/metrics.proto

package metrics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsIngestion_Ingest_FullMethodName       = "/metrics.MetricsIngestion/Ingest"
	MetricsIngestion_IngestStream_FullMethodName = "/metrics.MetricsIngestion/IngestStream"
)

// MetricsIngestionClient is the client API for MetricsIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsIngestionClient interface {
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestRequest, IngestResponse], error)
}

type metricsIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsIngestionClient(cc grpc.ClientConnInterface) MetricsIngestionClient {
	return &metricsIngestionClient{cc}
}

func (c *metricsIngestionClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, MetricsIngestion_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsIngestionClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestRequest, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsIngestion_ServiceDesc.Streams[0], MetricsIngestion_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestRequest, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsIngestion_IngestStreamClient = grpc.BidiStreamingClient[IngestRequest, IngestResponse]

// MetricsIngestionServer is the server API for MetricsIngestion service.
// All implementations must embed UnimplementedMetricsIngestionServer
// for forward compatibility.
type MetricsIngestionServer interface {
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	IngestStream(grpc.BidiStreamingServer[IngestRequest, IngestResponse]) error
	mustEmbedUnimplementedMetricsIngestionServer()
}

// UnimplementedMetricsIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsIngestionServer struct{}

func (UnimplementedMetricsIngestionServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedMetricsIngestionServer) IngestStream(grpc.BidiStreamingServer[IngestRequest, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedMetricsIngestionServer) mustEmbedUnimplementedMetricsIngestionServer() {}
func (UnimplementedMetricsIngestionServer) testEmbeddedByValue()                          {}

// UnsafeMetricsIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsIngestionServer will
// result in compilation errors.
type UnsafeMetricsIngestionServer interface {
	mustEmbedUnimplementedMetricsIngestionServer()
}

func RegisterMetricsIngestionServer(s grpc.ServiceRegistrar, srv MetricsIngestionServer) {
	// If the following call panics, it indicates UnimplementedMetricsIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsIngestion_ServiceDesc, srv)
}

func _MetricsIngestion_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsIngestionServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsIngestion_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsIngestionServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsIngestion_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsIngestionServer).IngestStream(&grpc.GenericServerStream[IngestRequest, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsIngestion_IngestStreamServer = grpc.BidiStreamingServer[IngestRequest, IngestResponse]

// MetricsIngestion_ServiceDesc is the grpc.ServiceDesc for MetricsIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricsIngestion",
	HandlerType: (*MetricsIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _MetricsIngestion_Ingest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _MetricsIngestion_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/metrics/metrics.proto",
}
