// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/notary/notary.proto

package notary

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerkleAnchor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleRoot    []byte                 `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`     // 32-byte SHA-256 Merkle root
	WindowStart   int64                  `protobuf:"varint,2,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"` // Unix ns — start of 10-min window
	WindowEnd     int64                  `protobuf:"varint,3,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	TxHash        string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`           // on-chain transaction hash
	IpfsCid       string                 `protobuf:"bytes,5,opt,name=ipfs_cid,json=ipfsCid,proto3" json:"ipfs_cid,omitempty"`        // IPFS CID of the full proof blob
	LeafCount     int64                  `protobuf:"varint,6,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count,omitempty"` // number of metrics in window
	Chain         string                 `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`                           // "ethereum" | "solana"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleAnchor) Reset() {
	*x = MerkleAnchor{}
	mi := &file_proto_notary_notary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleAnchor) ProtoMessage() {}

func (x *MerkleAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_notary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleAnchor.ProtoReflect.Descriptor instead.
func (*MerkleAnchor) Descriptor() ([]byte, []int) {
	return file_proto_notary_notary_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleAnchor) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *MerkleAnchor) GetWindowStart() int64 {
	if x != nil {
		return x.WindowStart
	}
	return 0
}

func (x *MerkleAnchor) GetWindowEnd() int64 {
	if x != nil {
		return x.WindowEnd
	}
	return 0
}

func (x *MerkleAnchor) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *MerkleAnchor) GetIpfsCid() string {
	if x != nil {
		return x.IpfsCid
	}
	return ""
}

func (x *MerkleAnchor) GetLeafCount() int64 {
	if x != nil {
		return x.LeafCount
	}
	return 0
}

func (x *MerkleAnchor) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type AnchorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowStart   int64                  `protobuf:"varint,1,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd     int64                  `protobuf:"varint,2,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorRequest) Reset() {
	*x = AnchorRequest{}
	mi := &file_proto_notary_notary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorRequest) ProtoMessage() {}

func (x *AnchorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_notary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorRequest.ProtoReflect.Descriptor instead.
func (*AnchorRequest) Descriptor() ([]byte, []int) {
	return file_proto_notary_notary_proto_rawDescGZIP(), []int{1}
}

func (x *AnchorRequest) GetWindowStart() int64 {
	if x != nil {
		return x.WindowStart
	}
	return 0
}

func (x *AnchorRequest) GetWindowEnd() int64 {
	if x != nil {
		return x.WindowEnd
	}
	return 0
}

type AnchorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchor        *MerkleAnchor          `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorResponse) Reset() {
	*x = AnchorResponse{}
	mi := &file_proto_notary_notary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorResponse) ProtoMessage() {}

func (x *AnchorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notary_notary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorResponse.ProtoReflect.Descriptor instead.
func (*AnchorResponse) Descriptor() ([]byte, []int) {
	return file_proto_notary_notary_proto_rawDescGZIP(), []int{2}
}

func (x *AnchorResponse) GetAnchor() *MerkleAnchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

var File_proto_notary_notary_proto protoreflect.FileDescriptor

const file_proto_notary_notary_proto_rawDesc = "" +
	"\n" +
	"\x19proto/notary/notary.proto\x12\x06notary\"\xda\x01\n" +
	"\fMerkleAnchor\x12\x1f\n" +
	"\vmerkle_root\x18\x01 \x01(\fR\n" +
	"merkleRoot\x12!\n" +
	"\fwindow_start\x18\x02 \x01(\x03R\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x03 \x01(\x03R\twindowEnd\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12\x19\n" +
	"\bipfs_cid\x18\x05 \x01(\tR\aipfsCid\x12\x1d\n" +
	"\n" +
	"leaf_count\x18\x06 \x01(\x03R\tleafCount\x12\x14\n" +
	"\x05chain\x18\a \x01(\tR\x05chain\"Q\n" +
	"\rAnchorRequest\x12!\n" +
	"\fwindow_start\x18\x01 \x01(\x03R\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x02 \x01(\x03R\twindowEnd\">\n" +
	"\x0eAnchorResponse\x12,\n" +
	"\x06anchor\x18\x01 \x01(\v2\x14.notary.MerkleAnchorR\x06anchor2\x8a\x01\n" +
	"\rNotaryService\x12=\n" +
	"\fAnchorWindow\x12\x15.notary.AnchorRequest\x1a\x16.notary.AnchorResponse\x12:\n" +
	"\tGetAnchor\x12\x15.notary.AnchorRequest\x1a\x16.notary.AnchorResponseB/Z-github.com/FsocietyVoid/TrustTrace/proto/notaryb\x06proto3"

var (
	file_proto_notary_notary_proto_rawDescOnce sync.Once
	file_proto_notary_notary_proto_rawDescData []byte
)

func file_proto_notary_notary_proto_rawDescGZIP() []byte {
	file_proto_notary_notary_proto_rawDescOnce.Do(func() {
		file_proto_notary_notary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notary_notary_proto_rawDesc), len(file_proto_notary_notary_proto_rawDesc)))
	})
	return file_proto_notary_notary_proto_rawDescData
}

var file_proto_notary_notary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_notary_notary_proto_goTypes = []any{
	(*MerkleAnchor)(nil),   // 0: notary.MerkleAnchor
	(*AnchorRequest)(nil),  // 1: notary.AnchorRequest
	(*AnchorResponse)(nil), // 2: notary.AnchorResponse
}
var file_proto_notary_notary_proto_depIdxs = []int32{
	0, // 0: notary.AnchorResponse.anchor:type_name -> notary.MerkleAnchor
	1, // 1: notary.NotaryService.AnchorWindow:input_type -> notary.AnchorRequest
	1, // 2: notary.NotaryService.GetAnchor:input_type -> notary.AnchorRequest
	2, // 3: notary.NotaryService.AnchorWindow:output_type -> notary.AnchorResponse
	2, // 4: notary.NotaryService.GetAnchor:output_type -> notary.AnchorResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_notary_notary_proto_init() }
func file_proto_notary_notary_proto_init() {
	if File_proto_notary_notary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notary_notary_proto_rawDesc), len(file_proto_notary_notary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notary_notary_proto_goTypes,
		DependencyIndexes: file_proto_notary_notary_proto_depIdxs,
		MessageInfos:      file_proto_notary_notary_proto_msgTypes,
	}.Build()
	File_proto_notary_notary_proto = out.File
	file_proto_notary_notary_proto_goTypes = nil
	file_proto_notary_notary_proto_depIdxs = nil
}
